# Generated by Django 5.1.4 on 2025-02-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Leads Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Leads Phone Number')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('domain', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Leads',
                'db_table': 'lead',
            },
        ),
    ]
