# Generated by Django 5.1.4 on 2025-02-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_leads_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='domain',
        ),
        migrations.AddField(
            model_name='leads',
            name='source',
            field=models.TextField(default=''),
        ),
    ]
