# Generated by Django 5.1.4 on 2025-02-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_leads_domain_leads_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
