# Generated by Django 5.1.4 on 2025-02-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_leads_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='email_error',
            field=models.TextField(default=''),
        ),
    ]
