# Generated by Django 5.1.4 on 2025-02-16 12:39

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.FileField(upload_to=website.models.blog_image_upload_path),
        ),
    ]
