# Generated by Django 5.1.4 on 2025-02-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='time_to_read',
            field=models.CharField(default='20 min', max_length=50),
        ),
    ]
