# Generated by Django 5.1.4 on 2025-02-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_blogs_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
