# Generated by Django 5.1.4 on 2025-02-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_emailcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='interested_in',
            field=models.CharField(choices=[('Seo', 'Seo'), ('Tech Development', 'Tech Development'), ('Web Development', 'Web Development'), ('Branding', 'Branding'), ('Lead Generation', 'Lead Generation'), ('Predictive Marketing Strategies', 'Predictive Marketing Strategies'), ('Marketing Strategies', 'Marketing Strategies'), ('B2B Manufacturing', 'B2B Manufacturing')], default='Seo', max_length=100),
        ),
    ]
