# Generated by Django 5.1.4 on 2025-02-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_leads_interested_in_alter_leads_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
