# Generated by Django 5.1.4 on 2025-02-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_emailcampaign_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcampaign',
            name='leads',
        ),
        migrations.CreateModel(
            name='LeadEmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Draft', max_length=100)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaign', to='website.emailtemplates')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_email_campaign', to='website.leads')),
            ],
            options={
                'verbose_name_plural': 'Lead Email Campaign',
                'db_table': 'lead_email_campaign',
            },
        ),
    ]
