# Generated by Django 5.1.4 on 2025-02-19 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_remove_emailcampaign_leads_leademailcampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leademailcampaign',
            name='email_template',
        ),
        migrations.AddField(
            model_name='leademailcampaign',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaign_fk', to='website.emailcampaign'),
        ),
    ]
