# Generated by Django 5.1.4 on 2025-02-23 14:48

import django.db.models.deletion
import uuid
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_leademailcampaign_email_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Converted To Customer', 'Converted To Customer'), ('On Hold', 'On Hold'), ('Follow Up', 'Follow Up'), ('Other', 'Other')], default='Draft', max_length=100),
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('model_id', models.PositiveBigIntegerField()),
                ('body', models.TextField()),
                ('subject', models.TextField()),
                ('signature', models.TextField()),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Email Sent', 'Email Sent'), ('Email Failed', 'Email Failed'), ('Email Received', 'Email Received'), ('Other', 'Other')], default='In Progress', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Emails',
                'db_table': 'emails',
            },
        ),
        migrations.CreateModel(
            name='EmailAttachments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=website.models.email_attachment_upload_path)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_attachment', to='website.emails')),
            ],
            options={
                'verbose_name_plural': 'Email Attachments',
                'db_table': 'email_attachment',
            },
        ),
        migrations.CreateModel(
            name='LoadLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_logs', to='website.leads')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lead Logs',
                'db_table': 'lead_logs',
            },
        ),
    ]
