# Generated by Django 5.1.4 on 2025-02-24 07:16

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_leads_status_emails_emailattachments_loadlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.FileField(max_length=500, upload_to=website.models.blog_image_upload_path),
        ),
    ]
