# Generated by Django 5.1.4 on 2025-02-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_blogs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
