# Generated by Django 5.1.4 on 2025-02-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_blogs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadlogs',
            name='activity_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
