# Generated by Django 5.1.4 on 2025-02-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_loadlogs_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
