# Generated by Django 5.1.4 on 2025-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_emails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='bcc',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emails',
            name='cc',
            field=models.CharField(blank=True, null=True),
        ),
    ]
