# Generated by Django 5.1.4 on 2025-02-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_emails_bcc_emails_cc'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailattachments',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
