# Generated by Django 5.1.4 on 2025-03-02 16:20

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_emailattachments_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=website.models.blog_image_upload_path),
        ),
    ]
