# Generated by Django 5.1.4 on 2025-03-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
