# Generated by Django 5.1.4 on 2025-03-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_alter_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='type',
            field=models.CharField(choices=[('Blog', 'Blog'), ('CaseStudy', 'CaseStudy')], default='Blog', max_length=200),
        ),
    ]
