# Generated by Django 5.1.4 on 2025-03-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_blogs_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
