# Generated by Django 5.1.4 on 2025-03-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_leads_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='email_error',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='location',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Leads Phone Number'),
        ),
        migrations.AlterField(
            model_name='leads',
            name='source',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
