# Generated by Django 5.1.4 on 2025-03-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_bulkleads'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkleads',
            name='log',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
