# Generated by Django 5.1.4 on 2025-03-12 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('website', '0030_bulkleads_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkleads',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulk_leads_company', to='company.company'),
        ),
    ]
