# Generated by Django 5.1.4 on 2025-03-13 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_bulkleads_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Leads Email')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_error', models.TextField(blank=True, default='', null=True)),
                ('custom_fields', models.JSONField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Email Sent', 'Email Sent'), ('Email Failed', 'Email Failed'), ('Email Received', 'Email Received'), ('Other', 'Other')], default='In Progress', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Email List',
                'db_table': 'email_list',
            },
        ),
        migrations.CreateModel(
            name='EmailCampaignMailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Draft', max_length=100)),
                ('meta_data', models.JSONField(blank=True, null=True)),
                ('email_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_campaign_fk', to='website.emailcampaign')),
                ('email_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_mail_list', to='website.emaillist')),
            ],
            options={
                'verbose_name_plural': 'Email Campaign Mail List',
                'db_table': 'email_campaign_list',
            },
        ),
        migrations.DeleteModel(
            name='LeadEmailCampaign',
        ),
    ]
