# Generated by Django 5.1.4 on 2025-03-13 01:58

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_emaillist_emailcampaignmaillist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=website.models.leads_upload_path),
        ),
    ]
