# Generated by Django 5.1.4 on 2025-03-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_emailcampaign_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnSubscribeEmailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Leads Email')),
            ],
        ),
        migrations.RemoveField(
            model_name='emailcampaign',
            name='file',
        ),
    ]
