# Generated by Django 5.1.4 on 2025-03-14 05:09

import django.db.models.deletion
import website.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_unsubscribeemaillist_remove_emailcampaign_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='unsubscribeemaillist',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Leads Email'),
        ),
        migrations.CreateModel(
            name='EmailCampaignFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=website.models.leads_upload_path)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_file', to='website.emailcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_file_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
