# Generated by Django 5.1.4 on 2025-03-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_alter_unsubscribeemaillist_email_emailcampaignfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaignmaillist',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Leads Email'),
        ),
        migrations.AddField(
            model_name='emailcampaignmaillist',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaignmaillist',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
