# Generated by Django 5.1.4 on 2025-03-14 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_emailcampaignmaillist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaignmaillist',
            name='email_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_mail_list', to='website.emaillist'),
        ),
    ]
