# Generated by Django 5.1.4 on 2025-03-15 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_clients_options_alter_clients_name_and_more'),
        ('website', '0037_alter_emailcampaignmaillist_email_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=250)),
                ('port', models.IntegerField(default=443)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.clients')),
            ],
            options={
                'verbose_name_plural': 'Email Accounts',
                'db_table': 'email_account',
            },
        ),
    ]
