# Generated by Django 5.1.4 on 2025-03-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_emailaccounts_created_at_emailaccounts_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
