# Generated by Django 5.1.4 on 2025-03-15 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_emailaccounts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='email_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.emailaccounts'),
        ),
    ]
