# Generated by Django 5.1.4 on 2025-03-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_emailcampaign_email_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='sender',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
