# Generated by Django 5.1.4 on 2025-03-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_emailaccounts_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
