# Generated by Django 5.1.4 on 2025-03-17 12:34

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_emails_email_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplates',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=website.models.upload_email_template_logo),
        ),
    ]
