# Generated by Django 5.1.4 on 2025-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0045_emailtemplates_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='sender_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
