# Generated by Django 5.1.4 on 2025-03-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_clients_options_alter_clients_name_and_more'),
        ('website', '0046_emailaccounts_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='bulkleads',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='emailattachments',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='emailcampaignfiles',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='emailcampaignmaillist',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='emaillist',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='emails',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='emailtemplates',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='leads',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='loadlogs',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='unsubscribeemaillist',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
    ]
