# Generated by Django 5.1.4 on 2025-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0048_alter_leads_interested_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='interested_in',
            field=models.CharField(choices=[('Seo', 'Seo'), ('Tech Development', 'Tech Development'), ('Web Development', 'Web Development'), ('Branding', 'Branding'), ('Lead Generation', 'Lead Generation'), ('Predictive Marketing Strategies', 'Predictive Marketing Strategies'), ('Marketing Strategies', 'Marketing Strategies'), ('B2B Manufacturing', 'B2B Manufacturing'), ('Website in 3 Days', 'Website in 3 Days'), ('Other', 'Other')], default='Seo', max_length=100),
        ),
    ]
