# Generated by Django 5.1.4 on 2025-04-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0049_alter_leads_interested_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccounts',
            name='connection_type',
            field=models.CharField(choices=[('TLS', 'TLS'), ('SSL', 'SSL')], default='SSL', max_length=50),
        ),
    ]
