from django.urls import path
from .views import *


urlpatterns = [
    path("accounts/tax_template", TaxTemplateListView.as_view(), name="tax_template_list"),
    path("accounts/tax_template/<str:pk>", TaxTemplateDetailsView.as_view(), name="tax_template_detail"),
    path("accounts/item/edit/<str:pk>", ItemsDetailsView.as_view(), name="item_detail"),
    path("accounts/item", ItemsListView.as_view(), name="item_list"),
    path("accounts/item/new", ItemsCreateView.as_view(), name="item_create"),
    path("accounts/terms_and_condition/edit/<str:pk>", TermsAndConditionsDetailsView.as_view(), name="terms_and_condition_details"),
    path("accounts/terms_and_condition", TermsAndConditionsListView.as_view(), name="terms_and_condition_list"),
    path("accounts/terms_and_condition/new", TermsAndConditionsCreateView.as_view(), name="terms_and_condition_create"),
    path("accounts/customer/edit/<str:pk>", CustomerDetailsView.as_view(), name="customer_details"),
    path("accounts/customer", CustomerListView.as_view(), name="customer_list"),
    path("accounts/customer/new", CustomerCreateView.as_view(), name="customer_create"),
    path("accounts/address/edit/<str:pk>", AddressDetailsView.as_view(), name="address_details"),
    path("accounts/address", AddressListView.as_view(), name="address_list"),
    path("accounts/address/new", AddressCreateView.as_view(), name="address_create"),
    path("accounts/quotation", QuotationListView.as_view(), name="quotation_list"),
    path("accounts/quotation/new", QuotationCreateView.as_view(), name="quotation_create"),
    path("accounts/quotation/edit/<str:pk>", QuotationDetailsView.as_view(), name="quotation_details"),
    path('api/address/', get_address_list, name='get_address_list'),
    path('api/customer/', get_customer_list, name='get_customer_list'),
    path('api/item/', get_items_list, name='item_list_api'),
    path('api/item/<int:pk>', get_item, name='item'),
    path('api/item/list/<str:site_key>', get_item_list, name='item-list'),
    path('api/customer/<int:pk>', get_customer, name='get_customer'),
    path('api/company/<int:pk>', get_company, name='get_company'),
    path('api/company/', get_company_list, name='get_company_list'),
    path('api/save-quotation/', save_quotation, name='save_quotation'),
    path('approve_quotation/<str:pk>', approve_quotation, name='approve_quotation'),
    path('accounts/quotation/print/<str:pk>', quotation_print_template, name='quotation_print_template'),
    path("accounts/invoice", InvoiceListView.as_view(), name="invoice_list"),
    path("accounts/invoice/new", InvoiceCreateView.as_view(), name="invoice_create"),
    path("accounts/invoice/edit/<str:pk>", InvoiceDetailsView.as_view(), name="invoice_details"),
    path('api/save-invoice/', save_invoice, name='save_invoice'),
    path('approve_invoice/<str:pk>', approve_invoice, name='approve_invoice'),
    path('accounts/invoice/print/<str:pk>', invoice_print_template, name='invoice_print_template'),
    path('accounts/payment/collection', PaymentCollectionLinksView.as_view(), name='payment_collection'),
    path('accounts/payment/links', PaymentCollectionLinksListView.as_view(), name='payment_collection_links'),
    path('accounts/payment/links/<str:pk>', PaymentCollectionLinksDetailsView.as_view(), name='payment_collection_links_details'),
]
