# Generated by Django 5.1.4 on 2025-03-30 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
        ('user', '0003_alter_clients_options_alter_clients_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='customer',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='items',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='quotationitems',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='taxtemplate',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='taxtemplateitems',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
    ]
