# Generated by Django 5.1.4 on 2025-03-30 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_address_client_customer_client_items_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='is_igst_item',
        ),
        migrations.AddField(
            model_name='items',
            name='igst_tax_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='igst_tax_template', to='erp.taxtemplate'),
        ),
        migrations.AlterField(
            model_name='items',
            name='tax_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_tax_template', to='erp.taxtemplate'),
        ),
    ]
