# Generated by Django 5.1.4 on 2025-03-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_address_email_alter_address_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, to='erp.address'),
        ),
    ]
