# Generated by Django 5.1.4 on 2025-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_remove_customer_address_customer_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('DOLLAR', 'DOLLAR')], default='INR', max_length=100),
        ),
    ]
