# Generated by Django 5.1.4 on 2025-04-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_customer_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitems',
            old_name='price',
            new_name='price_in_dollar',
        ),
        migrations.AddField(
            model_name='quotationitems',
            name='price_in_rs',
            field=models.FloatField(default=0.0),
        ),
    ]
