# Generated by Django 5.1.4 on 2025-04-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_rename_price_quotationitems_price_in_dollar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='gst_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
