# Generated by Django 5.1.4 on 2025-04-02 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_bankdetails_account_name_bankdetails_swift_code'),
        ('erp', '0010_quotation_approved_date_quotation_approver'),
        ('user', '0003_alter_clients_options_alter_clients_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('On Hold', 'On Hold')], default='Draft', max_length=50),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('po_no', models.CharField(blank=True, max_length=100, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved'), ('On Hold', 'On Hold')], default='Draft', max_length=50)),
                ('net_amount', models.FloatField(default=0.0)),
                ('discount_percentage', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('gross_amount', models.FloatField(default=0.0)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('tax_data', models.JSONField(default=None)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('bank_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_bank_details', to='company.bankdetails')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_billing_address', to='erp.address')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_%(class)ss', to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_customer', to='erp.customer')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_shipping_address', to='erp.address')),
                ('terms_and_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_terms_and_condition', to='erp.termsandconditions')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice',
                'db_table': 'invoice',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.FloatField(default=0.0)),
                ('price_in_rs', models.FloatField(default=0.0)),
                ('price_in_dollar', models.FloatField(default=0.0)),
                ('discount_per', models.FloatField(default=0.0)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('net_amount', models.FloatField(default=0.0)),
                ('gross_amount', models.FloatField(default=0.0)),
                ('tax_amount', models.FloatField(default=0.0)),
                ('tax_data', models.JSONField(default=None)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_%(class)ss', to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item_fk', to='erp.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='erp.items')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'invoice_items',
            },
        ),
    ]
