# Generated by Django 5.1.4 on 2025-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_quotation_status_invoice_invoiceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
