# Generated by Django 5.1.4 on 2025-04-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_activitylogs_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
