# Generated by Django 5.1.4 on 2025-04-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_paymentcollectionlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcollectionlinks',
            name='currency',
            field=models.CharField(choices=[('INR', 'INR'), ('DOLLAR', 'DOLLAR')], default='INR', max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentcollectionlinks',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Generated', 'Generated'), ('Paid', 'Paid'), ('Draft', 'Draft')], max_length=100),
        ),
    ]
