# Generated by Django 5.1.4 on 2025-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_paymentcollectionlinks_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
