# Generated by Django 5.1.4 on 2025-04-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_invoice_total_amount_quotation_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_no',
            field=models.CharField(blank=True, null=True),
        ),
    ]
