# Generated by Django 5.1.4 on 2025-04-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_quotation_quotation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='meta_data',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
