# Generated by Django 5.1.4 on 2025-04-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0021_alter_items_meta_data_itemimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
