# Generated by Django 5.1.4 on 2025-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_items_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
