# Generated by Django 5.1.4 on 2025-03-30 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_bankdetails_client'),
        ('user', '0003_alter_clients_options_alter_clients_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.clients'),
        ),
    ]
