# Generated by Django 5.1.4 on 2025-04-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='account_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='swift_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
