# Generated by Django 5.1.4 on 2025-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff_clients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterModelTable(
            name='clients',
            table='clients',
        ),
    ]
