# Generated by Django 5.1.4 on 2025-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
