# Generated by Django 5.1.4 on 2025-04-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='key',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
