# Generated by Django 5.1.4 on 2025-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_clients_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='permitted_modules',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
